title: Yuchen Du 的个人网站
email: yuchendu@example.com
description: >- 
  欢迎来到我的数字世界 - 全栈开发者的技术分享和创意作品展示
baseurl: "/yuchendu.github.io"
url: "https://dudusoar.github.io"

# 个人信息
author:
  name: Yuchen Du
  title: 全栈开发者
  subtitle: 技术爱好者 | 终身学习者
  
# 社交媒体
social:
  github: yuchendu
  twitter: yuchendu
  linkedin: yuchendu
  email: yuchendu@example.com

# 网站配置
site_config:
  background_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"
  primary_color: "#4fd1c7"
  
# 技能标签
skills:
  - JavaScript
  - TypeScript  
  - React
  - Vue.js
  - Node.js
  - Python
  - MongoDB
  - PostgreSQL
  - Docker
  - AWS
  - Git
  - Linux

# 统计数据
stats:
  projects: "50+"
  experience: "3"
  technologies: "15+"
  code_lines: "100K+"

# 构建设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 包含的目录
include:
  - assets

# 排除的文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# 分页设置
paginate: 5
paginate_path: "/blog/page:num/"

# 代码高亮
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge 