title: 你的个人网站
email: your-email@example.com
description: >- 
  欢迎来到我的数字世界 - 全栈开发者的技术分享和创意作品展示
baseurl: ""
url: "https://yuchendu.github.io"

# 个人信息
author:
  name: 你的名字
  title: 全栈开发者
  subtitle: 技术爱好者 | 终身学习者
  
# 社交媒体
social:
  github: yourusername
  twitter: yourusername
  linkedin: yourprofile
  email: your.email@example.com

# 构建设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 包含的目录
include:
  - assets
  - config.js

# 排除的文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# 分页设置
paginate: 5
paginate_path: "/blog/page:num/"

# 代码高亮
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge 